// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool.Repository.DataAccess;

#nullable disable

namespace SmartSchool.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240810063858_AddedClassLevelTableToDb")]
    partial class AddedClassLevelTableToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartSchool.Core.Models.ClassLevel", b =>
                {
                    b.Property<int>("LevelNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.HasKey("LevelNumber");

                    b.HasIndex("RoomNumber");

                    b.ToTable("ClassLevels");

                    b.HasData(
                        new
                        {
                            LevelNumber = 1,
                            Name = "Class One",
                            RoomNumber = 1001
                        },
                        new
                        {
                            LevelNumber = 2,
                            Name = "Class Two",
                            RoomNumber = 1002
                        },
                        new
                        {
                            LevelNumber = 3,
                            Name = "Class Three",
                            RoomNumber = 1003
                        },
                        new
                        {
                            LevelNumber = 4,
                            Name = "Class Four",
                            RoomNumber = 1004
                        },
                        new
                        {
                            LevelNumber = 5,
                            Name = "Class Five",
                            RoomNumber = 1005
                        },
                        new
                        {
                            LevelNumber = 6,
                            Name = "Class Six",
                            RoomNumber = 1006
                        },
                        new
                        {
                            LevelNumber = 7,
                            Name = "Class Seven",
                            RoomNumber = 1007
                        },
                        new
                        {
                            LevelNumber = 8,
                            Name = "Class Eight",
                            RoomNumber = 1008
                        });
                });

            modelBuilder.Entity("SmartSchool.Core.Models.CourseModels.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("SmartSchool.Core.Models.RoomModels.Room", b =>
                {
                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("RoomType")
                        .HasColumnType("int");

                    b.HasKey("RoomNumber");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomNumber = 1001,
                            Capacity = 50,
                            Description = "Room for Class One",
                            IsAvailable = true,
                            RoomType = 0
                        },
                        new
                        {
                            RoomNumber = 1002,
                            Capacity = 50,
                            Description = "Room for Class Two",
                            IsAvailable = true,
                            RoomType = 0
                        },
                        new
                        {
                            RoomNumber = 1003,
                            Capacity = 50,
                            Description = "Room for Class Three",
                            IsAvailable = true,
                            RoomType = 0
                        },
                        new
                        {
                            RoomNumber = 1004,
                            Capacity = 50,
                            Description = "Room for Class Four",
                            IsAvailable = true,
                            RoomType = 0
                        },
                        new
                        {
                            RoomNumber = 1005,
                            Capacity = 50,
                            Description = "Room for Class Five",
                            IsAvailable = true,
                            RoomType = 0
                        },
                        new
                        {
                            RoomNumber = 1006,
                            Capacity = 50,
                            Description = "Room for Class Six",
                            IsAvailable = true,
                            RoomType = 0
                        },
                        new
                        {
                            RoomNumber = 1007,
                            Capacity = 50,
                            Description = "Room for Class Seven",
                            IsAvailable = true,
                            RoomType = 0
                        },
                        new
                        {
                            RoomNumber = 1008,
                            Capacity = 50,
                            Description = "Room for Class Eight",
                            IsAvailable = true,
                            RoomType = 0
                        },
                        new
                        {
                            RoomNumber = 2001,
                            Capacity = 1,
                            Description = "Room for Teachers 2001",
                            IsAvailable = true,
                            RoomType = 5
                        },
                        new
                        {
                            RoomNumber = 2002,
                            Capacity = 1,
                            Description = "Room for Teachers 2002",
                            IsAvailable = true,
                            RoomType = 5
                        },
                        new
                        {
                            RoomNumber = 2003,
                            Capacity = 1,
                            Description = "Room for Teachers 2003",
                            IsAvailable = true,
                            RoomType = 5
                        },
                        new
                        {
                            RoomNumber = 2004,
                            Capacity = 1,
                            Description = "Room for Teachers 2004",
                            IsAvailable = true,
                            RoomType = 5
                        },
                        new
                        {
                            RoomNumber = 2005,
                            Capacity = 1,
                            Description = "Room for Teachers 2005",
                            IsAvailable = true,
                            RoomType = 5
                        },
                        new
                        {
                            RoomNumber = 2006,
                            Capacity = 1,
                            Description = "Room for Teachers 2006",
                            IsAvailable = true,
                            RoomType = 5
                        },
                        new
                        {
                            RoomNumber = 2007,
                            Capacity = 1,
                            Description = "Room for Teachers 2007",
                            IsAvailable = true,
                            RoomType = 5
                        },
                        new
                        {
                            RoomNumber = 2008,
                            Capacity = 1,
                            Description = "Room for Teachers 2008",
                            IsAvailable = true,
                            RoomType = 5
                        },
                        new
                        {
                            RoomNumber = 2009,
                            Capacity = 1,
                            Description = "Room for Teachers 2009",
                            IsAvailable = true,
                            RoomType = 5
                        },
                        new
                        {
                            RoomNumber = 2010,
                            Capacity = 1,
                            Description = "Room for Teachers 2010",
                            IsAvailable = true,
                            RoomType = 5
                        },
                        new
                        {
                            RoomNumber = 3001,
                            Capacity = 50,
                            Description = "Common Room",
                            IsAvailable = true,
                            RoomType = 3
                        },
                        new
                        {
                            RoomNumber = 3002,
                            Capacity = 50,
                            Description = "Common Room",
                            IsAvailable = true,
                            RoomType = 3
                        },
                        new
                        {
                            RoomNumber = 4001,
                            Capacity = 300,
                            Description = "Seminar Room",
                            IsAvailable = true,
                            RoomType = 1
                        },
                        new
                        {
                            RoomNumber = 5001,
                            Capacity = 50,
                            Description = "Meeting Room for Teachers",
                            IsAvailable = true,
                            RoomType = 2
                        },
                        new
                        {
                            RoomNumber = 6001,
                            Capacity = 100,
                            Description = "Sports Room",
                            IsAvailable = true,
                            RoomType = 7
                        },
                        new
                        {
                            RoomNumber = 6002,
                            Capacity = 100,
                            Description = "Sports Room",
                            IsAvailable = true,
                            RoomType = 7
                        },
                        new
                        {
                            RoomNumber = 7001,
                            Capacity = 10,
                            Description = "Register Room",
                            IsAvailable = true,
                            RoomType = 4
                        },
                        new
                        {
                            RoomNumber = 8001,
                            Capacity = 100,
                            Description = "Store Room",
                            IsAvailable = true,
                            RoomType = 6
                        },
                        new
                        {
                            RoomNumber = 9001,
                            Capacity = 10,
                            Description = "Staff Room",
                            IsAvailable = true,
                            RoomType = 8
                        },
                        new
                        {
                            RoomNumber = 9002,
                            Capacity = 10,
                            Description = "Staff Room",
                            IsAvailable = true,
                            RoomType = 8
                        });
                });

            modelBuilder.Entity("SmartSchool.Core.Models.StudentModels.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClassLevelNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassLevelNumber");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SmartSchool.Core.Models.TeacherModels.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("Designation")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SmartSchool.Core.Models.ClassLevel", b =>
                {
                    b.HasOne("SmartSchool.Core.Models.RoomModels.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartSchool.Core.Models.StudentModels.Student", b =>
                {
                    b.HasOne("SmartSchool.Core.Models.ClassLevel", "ClassLevel")
                        .WithMany("Students")
                        .HasForeignKey("ClassLevelNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassLevel");
                });

            modelBuilder.Entity("SmartSchool.Core.Models.ClassLevel", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
