// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool.Repository.DataAccess;

#nullable disable

namespace SmartSchool.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240811133632_SavingEnumAsStringsAndSeedStudentAndTeacherTable")]
    partial class SavingEnumAsStringsAndSeedStudentAndTeacherTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartSchool.Core.Models.ClassLevel", b =>
                {
                    b.Property<int>("LevelNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.HasKey("LevelNumber");

                    b.HasIndex("RoomNumber");

                    b.ToTable("ClassLevels");

                    b.HasData(
                        new
                        {
                            LevelNumber = 1,
                            Name = "Class One",
                            RoomNumber = 1001
                        },
                        new
                        {
                            LevelNumber = 2,
                            Name = "Class Two",
                            RoomNumber = 1002
                        },
                        new
                        {
                            LevelNumber = 3,
                            Name = "Class Three",
                            RoomNumber = 1003
                        },
                        new
                        {
                            LevelNumber = 4,
                            Name = "Class Four",
                            RoomNumber = 1004
                        },
                        new
                        {
                            LevelNumber = 5,
                            Name = "Class Five",
                            RoomNumber = 1005
                        },
                        new
                        {
                            LevelNumber = 6,
                            Name = "Class Six",
                            RoomNumber = 1006
                        },
                        new
                        {
                            LevelNumber = 7,
                            Name = "Class Seven",
                            RoomNumber = 1007
                        },
                        new
                        {
                            LevelNumber = 8,
                            Name = "Class Eight",
                            RoomNumber = 1008
                        });
                });

            modelBuilder.Entity("SmartSchool.Core.Models.CourseModels.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassLevelNumber")
                        .HasColumnType("int");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassLevelNumber");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassLevelNumber = 1,
                            CourseCode = "Ban-1",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "Bangla-I",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ClassLevelNumber = 1,
                            CourseCode = "Eng-1",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "English-I",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ClassLevelNumber = 1,
                            CourseCode = "Math-1",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "Mathematics-I",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            ClassLevelNumber = 1,
                            CourseCode = "Rel-1",
                            CourseType = "Optional",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an optional course.",
                            IsTaken = false,
                            Name = "Religion-I",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            ClassLevelNumber = 2,
                            CourseCode = "Ban-2",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "Bangla-II",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            ClassLevelNumber = 2,
                            CourseCode = "Eng-2",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "English-II",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            ClassLevelNumber = 2,
                            CourseCode = "Math-2",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "Mathematics-II",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            ClassLevelNumber = 2,
                            CourseCode = "Rel-2",
                            CourseType = "Optional",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an optional course.",
                            IsTaken = false,
                            Name = "Religion-II",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            ClassLevelNumber = 3,
                            CourseCode = "Ban-3",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "Bangla-III",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            ClassLevelNumber = 3,
                            CourseCode = "Eng-3",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "English-III",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            ClassLevelNumber = 3,
                            CourseCode = "Math-3",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "Mathematics-III",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            ClassLevelNumber = 3,
                            CourseCode = "Rel-3",
                            CourseType = "Optional",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an optional course.",
                            IsTaken = false,
                            Name = "Religion-III",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            ClassLevelNumber = 4,
                            CourseCode = "Ban-4",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "Bangla-IV",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            ClassLevelNumber = 4,
                            CourseCode = "Eng-4",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "English-IV",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            ClassLevelNumber = 4,
                            CourseCode = "Math-4",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "Mathematics-IV",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            ClassLevelNumber = 4,
                            CourseCode = "Rel-4",
                            CourseType = "Optional",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an optional course.",
                            IsTaken = false,
                            Name = "Religion-IV",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            ClassLevelNumber = 5,
                            CourseCode = "Ban-5",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "Bangla-V",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            ClassLevelNumber = 5,
                            CourseCode = "Eng-5",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "English-V",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            ClassLevelNumber = 5,
                            CourseCode = "Math-5",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "Mathematics-V",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            ClassLevelNumber = 5,
                            CourseCode = "Rel-5",
                            CourseType = "Optional",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an optional course.",
                            IsTaken = false,
                            Name = "Religion-V",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            ClassLevelNumber = 6,
                            CourseCode = "Ban-6",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "Bangla-VI",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            ClassLevelNumber = 6,
                            CourseCode = "Eng-6",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "English-VI",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            ClassLevelNumber = 6,
                            CourseCode = "Math-6",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "Mathematics-VI",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            ClassLevelNumber = 6,
                            CourseCode = "Rel-6",
                            CourseType = "Optional",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an optional course.",
                            IsTaken = false,
                            Name = "Religion-VI",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            ClassLevelNumber = 7,
                            CourseCode = "Ban-7",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "Bangla-VII",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            ClassLevelNumber = 7,
                            CourseCode = "Eng-7",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "English-VII",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            ClassLevelNumber = 7,
                            CourseCode = "Math-7",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "Mathematics-VII",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            ClassLevelNumber = 7,
                            CourseCode = "Rel-7",
                            CourseType = "Optional",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an optional course.",
                            IsTaken = false,
                            Name = "Religion-VII",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            ClassLevelNumber = 8,
                            CourseCode = "Ban-8",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "Bangla-VIII",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            ClassLevelNumber = 8,
                            CourseCode = "Eng-8",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "English-VIII",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            ClassLevelNumber = 8,
                            CourseCode = "Math-8",
                            CourseType = "Regular",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an regular course.",
                            IsTaken = false,
                            Name = "Mathematics-VIII",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            ClassLevelNumber = 8,
                            CourseCode = "Rel-8",
                            CourseType = "Optional",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is an optional course.",
                            IsTaken = false,
                            Name = "Religion-VIII",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SmartSchool.Core.Models.RoomModels.Room", b =>
                {
                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomNumber");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomNumber = 1001,
                            Capacity = 50,
                            Description = "Room for Class One",
                            IsAvailable = true,
                            RoomType = "ClassRoom"
                        },
                        new
                        {
                            RoomNumber = 1002,
                            Capacity = 50,
                            Description = "Room for Class Two",
                            IsAvailable = true,
                            RoomType = "ClassRoom"
                        },
                        new
                        {
                            RoomNumber = 1003,
                            Capacity = 50,
                            Description = "Room for Class Three",
                            IsAvailable = true,
                            RoomType = "ClassRoom"
                        },
                        new
                        {
                            RoomNumber = 1004,
                            Capacity = 50,
                            Description = "Room for Class Four",
                            IsAvailable = true,
                            RoomType = "ClassRoom"
                        },
                        new
                        {
                            RoomNumber = 1005,
                            Capacity = 50,
                            Description = "Room for Class Five",
                            IsAvailable = true,
                            RoomType = "ClassRoom"
                        },
                        new
                        {
                            RoomNumber = 1006,
                            Capacity = 50,
                            Description = "Room for Class Six",
                            IsAvailable = true,
                            RoomType = "ClassRoom"
                        },
                        new
                        {
                            RoomNumber = 1007,
                            Capacity = 50,
                            Description = "Room for Class Seven",
                            IsAvailable = true,
                            RoomType = "ClassRoom"
                        },
                        new
                        {
                            RoomNumber = 1008,
                            Capacity = 50,
                            Description = "Room for Class Eight",
                            IsAvailable = true,
                            RoomType = "ClassRoom"
                        },
                        new
                        {
                            RoomNumber = 2001,
                            Capacity = 1,
                            Description = "Room for Teachers 2001",
                            IsAvailable = true,
                            RoomType = "TeacherRoom"
                        },
                        new
                        {
                            RoomNumber = 2002,
                            Capacity = 1,
                            Description = "Room for Teachers 2002",
                            IsAvailable = true,
                            RoomType = "TeacherRoom"
                        },
                        new
                        {
                            RoomNumber = 2003,
                            Capacity = 1,
                            Description = "Room for Teachers 2003",
                            IsAvailable = true,
                            RoomType = "TeacherRoom"
                        },
                        new
                        {
                            RoomNumber = 2004,
                            Capacity = 1,
                            Description = "Room for Teachers 2004",
                            IsAvailable = true,
                            RoomType = "TeacherRoom"
                        },
                        new
                        {
                            RoomNumber = 2005,
                            Capacity = 1,
                            Description = "Room for Teachers 2005",
                            IsAvailable = true,
                            RoomType = "TeacherRoom"
                        },
                        new
                        {
                            RoomNumber = 2006,
                            Capacity = 1,
                            Description = "Room for Teachers 2006",
                            IsAvailable = true,
                            RoomType = "TeacherRoom"
                        },
                        new
                        {
                            RoomNumber = 2007,
                            Capacity = 1,
                            Description = "Room for Teachers 2007",
                            IsAvailable = true,
                            RoomType = "TeacherRoom"
                        },
                        new
                        {
                            RoomNumber = 2008,
                            Capacity = 1,
                            Description = "Room for Teachers 2008",
                            IsAvailable = true,
                            RoomType = "TeacherRoom"
                        },
                        new
                        {
                            RoomNumber = 2009,
                            Capacity = 1,
                            Description = "Room for Teachers 2009",
                            IsAvailable = true,
                            RoomType = "TeacherRoom"
                        },
                        new
                        {
                            RoomNumber = 2010,
                            Capacity = 1,
                            Description = "Room for Teachers 2010",
                            IsAvailable = true,
                            RoomType = "TeacherRoom"
                        },
                        new
                        {
                            RoomNumber = 3001,
                            Capacity = 50,
                            Description = "Common Room",
                            IsAvailable = true,
                            RoomType = "CommonRoom"
                        },
                        new
                        {
                            RoomNumber = 3002,
                            Capacity = 50,
                            Description = "Common Room",
                            IsAvailable = true,
                            RoomType = "CommonRoom"
                        },
                        new
                        {
                            RoomNumber = 4001,
                            Capacity = 300,
                            Description = "Seminar Room",
                            IsAvailable = true,
                            RoomType = "SeminarRoom"
                        },
                        new
                        {
                            RoomNumber = 5001,
                            Capacity = 50,
                            Description = "Meeting Room for Teachers",
                            IsAvailable = true,
                            RoomType = "MeetingRoom"
                        },
                        new
                        {
                            RoomNumber = 6001,
                            Capacity = 100,
                            Description = "Sports Room",
                            IsAvailable = true,
                            RoomType = "SportsRoom"
                        },
                        new
                        {
                            RoomNumber = 6002,
                            Capacity = 100,
                            Description = "Sports Room",
                            IsAvailable = true,
                            RoomType = "SportsRoom"
                        },
                        new
                        {
                            RoomNumber = 7001,
                            Capacity = 10,
                            Description = "Register Room",
                            IsAvailable = true,
                            RoomType = "RegisterRoom"
                        },
                        new
                        {
                            RoomNumber = 8001,
                            Capacity = 100,
                            Description = "Store Room",
                            IsAvailable = true,
                            RoomType = "StoreRoom"
                        },
                        new
                        {
                            RoomNumber = 9001,
                            Capacity = 10,
                            Description = "Staff Room",
                            IsAvailable = true,
                            RoomType = "StaffRoom"
                        },
                        new
                        {
                            RoomNumber = 9002,
                            Capacity = 10,
                            Description = "Staff Room",
                            IsAvailable = true,
                            RoomType = "StaffRoom"
                        });
                });

            modelBuilder.Entity("SmartSchool.Core.Models.StudentModels.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClassLevelNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassLevelNumber");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Dhaka",
                            ClassLevelNumber = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Gender = "Male",
                            Name = "Asif",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Gazipur",
                            ClassLevelNumber = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Gender = "Female",
                            Name = "Hinata",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Dhaka",
                            ClassLevelNumber = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Gender = "Male",
                            Name = "Naruto",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Gazipur",
                            ClassLevelNumber = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Gender = "Female",
                            Name = "Sakura",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Dhaka",
                            ClassLevelNumber = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Gender = "Male",
                            Name = "Neji",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Address = "Gazipur",
                            ClassLevelNumber = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Gender = "Female",
                            Name = "Rock Lee",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Address = "Dhaka",
                            ClassLevelNumber = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Gender = "Male",
                            Name = "Shikamaru",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Address = "Gazipur",
                            ClassLevelNumber = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Gender = "Female",
                            Name = "Choji",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Address = "Dhaka",
                            ClassLevelNumber = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Gender = "Male",
                            Name = "Kiba",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Address = "Gazipur",
                            ClassLevelNumber = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Gender = "Female",
                            Name = "Akamaru",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Address = "Dhaka",
                            ClassLevelNumber = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Gender = "Male",
                            Name = "Ino",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Address = "Gazipur",
                            ClassLevelNumber = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Gender = "Female",
                            Name = "Suske",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Address = "Dhaka",
                            ClassLevelNumber = 7,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Gender = "Male",
                            Name = "Gaara",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Address = "Gazipur",
                            ClassLevelNumber = 7,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Gender = "Female",
                            Name = "Temari",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Address = "Dhaka",
                            ClassLevelNumber = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Gender = "Male",
                            Name = "Kankuro",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Address = "Gazipur",
                            ClassLevelNumber = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Gender = "Female",
                            Name = "Konohamaru",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SmartSchool.Core.Models.TeacherModels.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Dhaka",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Designation = "Professor",
                            Gender = "Male",
                            Name = "Jiraiya",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Gazipur",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Designation = "Professor",
                            Gender = "Female",
                            Name = "Tsunade",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Dhaka",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Designation = "Professor",
                            Gender = "Male",
                            Name = "Hiruzen",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Gazipur",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Designation = "Professor",
                            Gender = "Female",
                            Name = "Minato",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Dhaka",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Designation = "AssociateProfessor",
                            Gender = "Male",
                            Name = "Kahashi Sensei",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Address = "Gazipur",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Designation = "AssociateProfessor",
                            Gender = "Female",
                            Name = "Yamato",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Address = "Dhaka",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Designation = "AssociateProfessor",
                            Gender = "Male",
                            Name = "Might Guy",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Address = "Gazipur",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Designation = "AssociateProfessor",
                            Gender = "Female",
                            Name = "Asuma",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Address = "Dhaka",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Designation = "AssistantProfessor",
                            Gender = "Male",
                            Name = "Orochimaru",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Address = "Gazipur",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Designation = "AssistantProfessor",
                            Gender = "Female",
                            Name = "Nagato",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Address = "Dhaka",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Designation = "AssistantProfessor",
                            Gender = "Male",
                            Name = "Yahiko",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Address = "Gazipur",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Designation = "AssistantProfessor",
                            Gender = "Female",
                            Name = "Kisame",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Address = "Dhaka",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Designation = "Lecturer",
                            Gender = "Male",
                            Name = "Iruka Sensei",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Address = "Gazipur",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Designation = "Lecturer",
                            Gender = "Female",
                            Name = "Itachi Uchiha",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Address = "Dhaka",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Designation = "Lecturer",
                            Gender = "Male",
                            Name = "Deridara",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Address = "Gazipur",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 1, 20),
                            Designation = "Lecturer",
                            Gender = "Female",
                            Name = "Tobi",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SmartSchool.Core.Models.ClassLevel", b =>
                {
                    b.HasOne("SmartSchool.Core.Models.RoomModels.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartSchool.Core.Models.CourseModels.Course", b =>
                {
                    b.HasOne("SmartSchool.Core.Models.ClassLevel", "ClassLevel")
                        .WithMany("CourseList")
                        .HasForeignKey("ClassLevelNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.Core.Models.TeacherModels.Teacher", "Teacher")
                        .WithMany("CourseList")
                        .HasForeignKey("TeacherId");

                    b.Navigation("ClassLevel");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SmartSchool.Core.Models.StudentModels.Student", b =>
                {
                    b.HasOne("SmartSchool.Core.Models.ClassLevel", "ClassLevel")
                        .WithMany("StudentList")
                        .HasForeignKey("ClassLevelNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassLevel");
                });

            modelBuilder.Entity("SmartSchool.Core.Models.ClassLevel", b =>
                {
                    b.Navigation("CourseList");

                    b.Navigation("StudentList");
                });

            modelBuilder.Entity("SmartSchool.Core.Models.TeacherModels.Teacher", b =>
                {
                    b.Navigation("CourseList");
                });
#pragma warning restore 612, 618
        }
    }
}
